# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'test.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.

import api
from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtWidgets import QMessageBox

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 600)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.textTitle = QtWidgets.QTextBrowser(self.centralwidget)
        self.textTitle.setGeometry(QtCore.QRect(280, 20, 221, 51))
        self.textTitle.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.textTitle.setObjectName("textTitle")
        self.text_url = QtWidgets.QTextEdit(self.centralwidget)
        self.text_url.setGeometry(QtCore.QRect(110, 100, 661, 41))
        font = QtGui.QFont()
        font.setFamily("Adobe Devanagari")
        font.setPointSize(14)
        self.text_url.setFont(font)
        self.text_url.setObjectName("text_url")
        self.label_url = QtWidgets.QLabel(self.centralwidget)
        self.label_url.setGeometry(QtCore.QRect(20, 90, 101, 61))
        self.label_url.setObjectName("label_url")
        self.startButton = QtWidgets.QPushButton(self.centralwidget)
        self.startButton.setGeometry(QtCore.QRect(290, 270, 201, 61))
        self.startButton.setAutoDefault(True)
        self.startButton.setDefault(True)
        self.startButton.setObjectName("startButton")
        self.label_info = QtWidgets.QLabel(self.centralwidget)
        self.label_info.setGeometry(QtCore.QRect(50, 340, 681, 201))
        self.label_info.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label_info.setObjectName("label_info")
        self.clearButton = QtWidgets.QPushButton(self.centralwidget)
        self.clearButton.setGeometry(QtCore.QRect(670, 60, 93, 28))
        self.clearButton.setObjectName("clearButton")
        self.widget = QtWidgets.QWidget(self.centralwidget)
        self.widget.setGeometry(QtCore.QRect(150, 160, 501, 81))
        self.widget.setObjectName("widget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.widget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.radioButton_meitu131 = QtWidgets.QRadioButton(self.widget)
        font = QtGui.QFont()
        font.setFamily("Adobe Devanagari")
        font.setPointSize(24)
        self.radioButton_meitu131.setFont(font)
        self.radioButton_meitu131.setObjectName("radioButton_meitu131")
        self.horizontalLayout.addWidget(self.radioButton_meitu131)
        self.radioButton_weiyituku = QtWidgets.QRadioButton(self.widget)
        font = QtGui.QFont()
        font.setFamily("Adobe Devanagari")
        font.setPointSize(24)
        self.radioButton_weiyituku.setFont(font)
        self.radioButton_weiyituku.setObjectName("radioButton_weiyituku")
        self.horizontalLayout.addWidget(self.radioButton_weiyituku)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 26))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        self.clearButton.clicked.connect(self.text_url.clear)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

        self.startButton.clicked.connect(self.download)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.textTitle.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'SimSun\'; font-size:9pt; font-weight:400; font-style:normal;\">\n"
"<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:20pt; font-weight:600; color:#aaaa00;\">图片爬虫</span></p></body></html>"))
        self.label_url.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:24pt;\">URL：</span></p></body></html>"))
        self.startButton.setText(_translate("MainWindow", "开始下载"))
        self.label_info.setText(_translate("MainWindow", "已启动！%s" % api.localPath))
        self.clearButton.setText(_translate("MainWindow", "清空"))
        self.radioButton_meitu131.setText(_translate("MainWindow", "meitu131"))
        self.radioButton_weiyituku.setText(_translate("MainWindow", "唯一图库"))
    
    def download(self):
        self.url = self.text_url.toPlainText()
        if self.url == '':
            self.message_url()
        elif self.radioButton_meitu131.isChecked():
            self.select = '2'
            self.downpic()
        elif self.radioButton_weiyituku.isChecked():
            self.select = '1'
            self.downpic()
        else:
            self.message()

    def downpic(self):
        self.label_info.setText(str(self.label_info.text) + "\n正在下载中······\n")
        api.down(self.select, self.url)
        

    def message(self):
        msg = QMessageBox()
        msg.setWindowTitle("警告")
        msg.setText("未选择类型")
        msg.setIcon(QMessageBox.Warning)

        x = msg.exec_()
    def message_url(self):
        msg = QMessageBox()
        msg.setWindowTitle("警告")
        msg.setText("未填写URL！")
        msg.setIcon(QMessageBox.Warning)

        x = msg.exec_()
if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
